### ISSUE TITLE
Texts?

### ISSUE THREAD

**Issue by tin2tin** [FyorUU/PureRef-format#4]
How do I deal with texts I/O? 

I develop stories with chatGPT in a screenwriter add-on inside of Blender, but I easily get lost in all the directions the story can go, and I would like to arrange the story elements in an infinite canvas like pureref. If texts/notes are supported in your code, can you include how to deal with it I/O in your examples/documentation?

**Comment by FyorUU** [comment]
Text items are supported, although there are currently issues with parented text which I'm working on (but honestly I'm occupied in other programming projects rn so it may take a while).
I'd like to make an 'examples' folder in the future, but that's not here yet. There's an example of how to generate a file from scratch and transforms items however you want in `pureref_gen.py`.

You want to use the `PurGraphicsTextItem(Item)` class from `purformat.py`, you can just add a string to the `.text` and the `write(self, file: str):` will take care of encoding.
You probably want to place them next to each other, for which you can do some math with the `x` and `y` of the `Item` superclass, just like I did in `pureref_gen.py` to create files from scratch.

If you have trouble coding in Python, post what you manage and I'll point you in the right direction.

**Comment by tin2tin** [comment]
Thank you. Did an add-on for Blender, I may use that instead. But cool work you're doing here!

**Comment by FyorUU** [comment]
Thanks bro!
